import { app, BrowserWindow } from "electron";
if (require("electron-squirrel-startup")) app.quit();

import logger from "electron-log";
// Configure electron-log to not use preload script (we'll use our own preload)
logger.initialize({ preload: false });

import { updateElectronApp } from "update-electron-app";
updateElectronApp({ logger });

// IPC handlers
import "./config";
import "./chats";
import "./messages";
import "./courses";
import "./model";
import "./search"; // Search engine IPC handlers
import { deleteAllCurrentlyImportingDocuments } from "./documents";
import { registerErrorIPCHandlers } from "./errors/ipc-handlers";
import IPCHandlers from "./IPCHandlers";

// Startup and shutdown managers
import { StartupManager, ShutdownManager, SplashWindow } from "./startup";

const log = logger.log;

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// Webpack entry points are available as constants
// They will be used directly in StartupManager

/**
 * Application startup sequence with splash screen and first-run wizard
 */
async function startApplication(): Promise<void> {
  try {
    log("=== Pinguin Application Starting ===");

    // Register IPC handlers first
    registerErrorIPCHandlers();
    const ipcHandlers = IPCHandlers.getInstance();
    ipcHandlers.registerHandlers();

    // Create and show splash screen
    const splashWindow = new SplashWindow();
    const splash = splashWindow.create();

    // Initialize startup manager
    const startupManager = StartupManager.getInstance();
    startupManager.setSplashWindow(splash);

    // Execute startup sequence
    await startupManager.startup();

    // Get main window
    const mainWindow = startupManager.getMainWindow();

    // Close splash screen and show main window
    splashWindow.close();
    
    // Show main window (the React app will handle first-run wizard routing)
    if (mainWindow && !mainWindow.isVisible()) {
      mainWindow.show();
    }

    log("=== Pinguin Application Started ===");
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    log(`Application startup failed: ${errorMessage}`);
    
    // Show error dialog
    import("electron").then(({ dialog }) => {
      dialog.showErrorBox(
        "Startup Failed",
        `Pinguin failed to start:\n\n${errorMessage}\n\nPlease check the logs for more details.`
      );
      app.quit();
    }).catch(() => {
      // If dialog fails, just quit
      app.quit();
    });
  }
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  startApplication();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  const startupManager = StartupManager.getInstance();
  if (BrowserWindow.getAllWindows().length === 0 && startupManager.isReady()) {
    // If startup is complete but window was closed, just create a new window
    // This is a simplified approach - in production you might want to re-run startup
    log("Recreating window after activation");
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

/**
 * Graceful shutdown sequence
 */
let shutdownComplete = false;

app.on("before-quit", async (event) => {
  // If shutdown is already complete, allow quit
  if (shutdownComplete) {
    return;
  }

  const shutdownManager = ShutdownManager.getInstance();
  
  if (!shutdownManager.isShutdownInProgress()) {
    // Prevent immediate quit to allow graceful shutdown
    event.preventDefault();
    
    log("=== Starting Graceful Shutdown ===");
    
    try {
      // Clean up importing documents
      deleteAllCurrentlyImportingDocuments();
      
      // Execute graceful shutdown
      await shutdownManager.shutdown();
      
      log("=== Graceful Shutdown Complete ===");
      
      // Mark shutdown as complete before calling quit
      shutdownComplete = true;
      
      // Now allow the app to quit
      app.quit();
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      log(`Shutdown error: ${errorMessage}`);
      
      // Mark shutdown as complete even on error
      shutdownComplete = true;
      
      // Force quit even if shutdown fails
      app.quit();
    }
  }
});
